- hosts: localhost
  connection: local
  become: yes

  pre_tasks:

    - include: tasks/packages.yml
    - name: Upgrade to latest packages.
      apt:
        name: "*"
        state: latest


  tasks:

    #- include: tasks/packages.yml
    - include: tasks/dns.yml

  roles:

    - harden_server
    - tune_server
