- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Upgrade to latest packages.
      apt:
        name: "*"
        state: latest


  tasks:

    - include: tasks/packages.yml
    - include: tasks/dns.yml

  roles:

    - harden_server
