- name: Install additional packages.
  apt:
    name: '{{ packages }}'
    state: present
  vars:
    packages:
     - lynis
     - rkhunter
     - logwatch
     - rsyslog
     - net-snmp
     - htop
     - ntpdate
