---

- name: Get PowerBroker repo.
  get_url:
    url: http://repo.pbis.beyondtrust.com/yum/pbiso.repo
    dest: /etc/yum.repos.d/pbiso.repo
    mode: '644'
  become: yes

- name: Refresh packages repository and clean cash
  become: yes
  shell:
    cmd: /usr/bin/dnf clean all
  register: cleaner

- debug: msg="{{ cleaner.stdout }}"

- name: Install libnsl package required for pbis on Fedora.
  become: yes
  dnf:
    name: libnsl
    state: present

- name: Install pbis open for AD integration
  dnf:
    name: pbis-open
    state: present
  become: yes

- name: Start and enable lwsmd.services
  service:
    name: lwsmd
    state: started
    enabled: yes

- name: Create AD file and add users & groups
  become: yes
  blockinfile:
    dest: /etc/sudoers.d/AD
    create: yes
    block: |
      Defaults	timestamp_timeout=30
      %domain^admins ALL=(ALL:ALL) NOPASSWD:ALL
      %techops ALL=(ALL:ALL) NOPASSWD:ALL
      %netops ALL=(ALL:ALL) NOPASSWD:ALL

- name: Configure pbis
  become: yes
  shell: |
      /opt/pbis/bin/config enableeventlog true
      /opt/pbis/bin/config pamloglevel error
      /opt/pbis/bin/config homedirtemplate %H/%U
      /opt/pbis/bin/config local_homedirtemplate %H/%U
      /opt/pbis/bin/config loginshelltemplate /bin/bash
      /opt/pbis/bin/config requiremembershipof PTS\\Employees PTS\\Domain^Admins
      /opt/pbis/bin/config remotehomedirtemplate %H/%U/share_mount
      /opt/pbis/bin/config syncsystemtime false
      /opt/pbis/bin/config assumedefaultdomain true
      /opt/pbis/bin/config userdomainprefix PTS
      chmod 400 /etc/sudoers.d/AD

  notify:
      - restart PowerBroker
